[project]
name = "p-le-projet-zenkolab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=2.0.0",
    "pandas>=2.0.0",
    "lightning>=2.6.1",
    "pip>=26.0.1",
    "rich>=14.3.3",
    "timm>=1.0.25",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "uv>=0.10.9",
]
